"""
Merge pseudo-labels generated by DVPS and OW-DLN

This script intelligently merges DVPS segmentation results and OW-DLN detection results
to generate high-quality pseudo-labels for unknown categories.
"""

import numpy as np
from pathlib import Path
import argparse
from tqdm import tqdm
import cv2


def iou(box1, box2):
    """
    Calculate IoU of two bounding boxes
    
    Args:
        box1, box2: [x1, y1, x2, y2]
        
    Returns:
        float: IoU value
    """
    x1 = max(box1[0], box2[0])
    y1 = max(box1[1], box2[1])
    x2 = min(box1[2], box2[2])
    y2 = min(box1[3], box2[3])
    
    inter_area = max(0, x2 - x1) * max(0, y2 - y1)
    
    box1_area = (box1[2] - box1[0]) * (box1[3] - box1[1])
    box2_area = (box2[2] - box2[0]) * (box2[3] - box2[1])
    
    union_area = box1_area + box2_area - inter_area
    
    return inter_area / (union_area + 1e-6)


def yolo_to_xyxy(yolo_box, img_width, img_height):
    """
    Convert YOLO format to xyxy format
    
    Args:
        yolo_box: [class, x_center, y_center, width, height] (normalized)
        img_width, img_height: Image dimensions
        
    Returns:
        tuple: (class, x1, y1, x2, y2, conf)
    """
    cls = int(yolo_box[0])
    x_c, y_c, w, h = yolo_box[1:5]
    conf = yolo_box[5] if len(yolo_box) > 5 else 1.0
    
    x1 = int((x_c - w/2) * img_width)
    y1 = int((y_c - h/2) * img_height)
    x2 = int((x_c + w/2) * img_width)
    y2 = int((y_c + h/2) * img_height)
    
    return (cls, x1, y1, x2, y2, conf)


def xyxy_to_yolo(cls, x1, y1, x2, y2, img_width, img_height, conf=1.0):
    """
    Convert xyxy format to YOLO format
    
    Returns:
        str: YOLO format label line
    """
    x_c = ((x1 + x2) / 2) / img_width
    y_c = ((y1 + y2) / 2) / img_height
    w = (x2 - x1) / img_width
    h = (y2 - y1) / img_height
    
    # Ensure within [0, 1] range
    x_c = max(0, min(1, x_c))
    y_c = max(0, min(1, y_c))
    w = max(0, min(1, w))
    h = max(0, min(1, h))
    
    return f"{cls} {x_c:.6f} {y_c:.6f} {w:.6f} {h:.6f}"


def merge_labels(dvps_labels, owdln_labels, img_width, img_height, 
                 iou_threshold=0.5, conf_threshold=0.5, unknown_class_id=999):
    """
    Merge DVPS and OW-DLN labels
    
    Strategy:
    1. Regions detected by both DVPS and OW-DLN → Keep OW-DLN class and confidence
    2. Regions detected only by DVPS → Mark as unknown (unknown class)
    3. Regions detected only by OW-DLN → Keep (known classes)
    
    Args:
        dvps_labels: Label list generated by DVPS
        owdln_labels: Label list generated by OW-DLN
        img_width, img_height: Image dimensions
        iou_threshold: IoU threshold to determine if same object
        conf_threshold: Confidence threshold
        unknown_class_id: ID for unknown class
        
    Returns:
        list: Merged label list (YOLO format strings)
    """
    # Convert to xyxy format
    dvps_boxes = []
    for label in dvps_labels:
        parts = list(map(float, label.strip().split()))
        if len(parts) >= 5:
            dvps_boxes.append(yolo_to_xyxy(parts, img_width, img_height))
    
    owdln_boxes = []
    for label in owdln_labels:
        parts = list(map(float, label.strip().split()))
        if len(parts) >= 5:
            box = yolo_to_xyxy(parts, img_width, img_height)
            # Filter low confidence detections
            if box[5] >= conf_threshold:
                owdln_boxes.append(box)
    
    merged_labels = []
    matched_dvps = set()
    matched_owdln = set()
    
    # Step 1: Match DVPS and OW-DLN detections
    for i, dvps_box in enumerate(dvps_boxes):
        best_iou = 0
        best_match = -1
        
        for j, owdln_box in enumerate(owdln_boxes):
            if j in matched_owdln:
                continue
            
            iou_val = iou(dvps_box[1:5], owdln_box[1:5])
            if iou_val > best_iou and iou_val >= iou_threshold:
                best_iou = iou_val
                best_match = j
        
        if best_match >= 0:
            # Match successful, use OW-DLN result
            matched_dvps.add(i)
            matched_owdln.add(best_match)
            owdln_box = owdln_boxes[best_match]
            label = xyxy_to_yolo(owdln_box[0], *owdln_box[1:5], img_width, img_height, owdln_box[5])
            merged_labels.append(label)
    
    # Step 2: Add unmatched DVPS detections (mark as unknown)
    for i, dvps_box in enumerate(dvps_boxes):
        if i not in matched_dvps:
            # Detected by DVPS but not by OW-DLN, likely unknown class
            label = xyxy_to_yolo(unknown_class_id, *dvps_box[1:5], img_width, img_height, dvps_box[5])
            merged_labels.append(label)
    
    # Step 3: Add unmatched OW-DLN detections (known classes, high confidence)
    for j, owdln_box in enumerate(owdln_boxes):
        if j not in matched_owdln:
            # Detected by OW-DLN but not by DVPS, likely false detection or background
            # Only keep high confidence ones
            if owdln_box[5] >= 0.7:  # Higher threshold
                label = xyxy_to_yolo(owdln_box[0], *owdln_box[1:5], img_width, img_height, owdln_box[5])
                merged_labels.append(label)
    
    return merged_labels


def get_image_size(image_path, default_size=(640, 640)):
    """
    Get image dimensions
    
    Args:
        image_path: Image path
        default_size: Default size (if unable to read image)
        
    Returns:
        tuple: (width, height)
    """
    try:
        img = cv2.imread(str(image_path))
        if img is not None:
            h, w = img.shape[:2]
            return (w, h)
    except:
        pass
    
    return default_size


def process_labels(dvps_dir, owdln_dir, output_dir, image_dir=None,
                  iou_threshold=0.5, conf_threshold=0.5, unknown_class_id=999,
                  default_size=(640, 640)):
    """
    Batch process label merging
    
    Args:
        dvps_dir: DVPS label directory
        owdln_dir: OW-DLN label directory
        output_dir: Output directory
        image_dir: Image directory (for getting image dimensions)
        iou_threshold: IoU threshold
        conf_threshold: Confidence threshold
        unknown_class_id: Unknown class ID
        default_size: Default image size
    """
    dvps_dir = Path(dvps_dir)
    owdln_dir = Path(owdln_dir)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    if image_dir:
        image_dir = Path(image_dir)
    
    # Get all label files
    dvps_files = {f.stem: f for f in dvps_dir.glob('*.txt')}
    owdln_files = {f.stem: f for f in owdln_dir.glob('*.txt')}
    
    # Find common filenames
    common_names = set(dvps_files.keys()) | set(owdln_files.keys())
    
    print(f"DVPS labels: {len(dvps_files)}")
    print(f"OW-DLN labels: {len(owdln_files)}")
    print(f"Files to process: {len(common_names)}")
    
    stats = {
        'total': 0,
        'dvps_only': 0,
        'owdln_only': 0,
        'matched': 0,
        'unknown_generated': 0
    }
    
    for name in tqdm(common_names, desc="Merging labels"):
        # Read DVPS labels
        dvps_labels = []
        if name in dvps_files:
            with open(dvps_files[name], 'r') as f:
                dvps_labels = f.readlines()
        
        # Read OW-DLN labels
        owdln_labels = []
        if name in owdln_files:
            with open(owdln_files[name], 'r') as f:
                owdln_labels = f.readlines()
        
        # Get image dimensions
        if image_dir:
            img_path = None
            for ext in ['.jpg', '.png', '.jpeg', '.JPG', '.PNG']:
                potential_path = image_dir / f"{name}{ext}"
                if potential_path.exists():
                    img_path = potential_path
                    break
            
            if img_path:
                img_size = get_image_size(img_path, default_size)
            else:
                img_size = default_size
        else:
            img_size = default_size
        
        # Merge labels
        merged = merge_labels(
            dvps_labels, owdln_labels, 
            img_size[0], img_size[1],
            iou_threshold, conf_threshold, unknown_class_id
        )
        
        # Statistics
        stats['total'] += 1
        if len(dvps_labels) > 0 and len(owdln_labels) == 0:
            stats['dvps_only'] += 1
        if len(owdln_labels) > 0 and len(dvps_labels) == 0:
            stats['owdln_only'] += 1
        
        # Count unknown class
        for label in merged:
            cls = int(label.split()[0])
            if cls == unknown_class_id:
                stats['unknown_generated'] += 1
        
        # Save merged results
        output_path = output_dir / f"{name}.txt"
        with open(output_path, 'w') as f:
            f.write('\n'.join(merged))
    
    print("\nMerging complete!")
    print(f"Total files: {stats['total']}")
    print(f"DVPS only detections: {stats['dvps_only']}")
    print(f"OW-DLN only detections: {stats['owdln_only']}")
    print(f"Unknown class labels generated: {stats['unknown_generated']}")


def main():
    parser = argparse.ArgumentParser(description='Merge DVPS and OW-DLN pseudo-labels')
    parser.add_argument('--dvps_labels', type=str, required=True,
                       help='DVPS label directory')
    parser.add_argument('--owdln_labels', type=str, required=True,
                       help='OW-DLN label directory')
    parser.add_argument('--output_dir', type=str, required=True,
                       help='Output label directory')
    parser.add_argument('--image_dir', type=str,
                       help='Image directory (for getting image dimensions)')
    parser.add_argument('--iou_threshold', type=float, default=0.5,
                       help='IoU threshold (default: 0.5)')
    parser.add_argument('--confidence_threshold', type=float, default=0.5,
                       help='Confidence threshold (default: 0.5)')
    parser.add_argument('--unknown_class_id', type=int, default=999,
                       help='Unknown class ID (default: 999)')
    parser.add_argument('--default_width', type=int, default=640,
                       help='Default image width (default: 640)')
    parser.add_argument('--default_height', type=int, default=640,
                       help='Default image height (default: 640)')
    
    args = parser.parse_args()
    
    process_labels(
        dvps_dir=args.dvps_labels,
        owdln_dir=args.owdln_labels,
        output_dir=args.output_dir,
        image_dir=args.image_dir,
        iou_threshold=args.iou_threshold,
        conf_threshold=args.confidence_threshold,
        unknown_class_id=args.unknown_class_id,
        default_size=(args.default_width, args.default_height)
    )


if __name__ == '__main__':
    main()
